[phases.setup]
nixPkgs = ['...', 'bun']

[phases.build]
cmds = ['pnpm install --filter db', 'pnpm install --filter config', 'pnpm install --filter bot']

[start]
cmd = 'bun -v && pwd && pnpm --filter=bot run start'